on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: GitHub Releases to Discord
        uses: SethCohen/github-releases-to-discord@v1.20.0
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL_RELEASE }}
          color: "1441536"
          username: "Pazaak — Release"
          content: "<@&1504461952339148890>"
          footer_title: "Changelog"
          reduce_headings: true
          footer_timestamp: true
